-- Clipboard History Module for Hammerspoon
-- Monitors clipboard for text changes, stores history, provides a searchable webview UI
-- Skips password manager entries (ConcealedType, TransientType, etc.)
-- Entries older than max_age_days are automatically pruned

local M = {}
local htmlLoader = require("html_loader")

-- Config defaults
local config = {
    hotkey = {{"ctrl", "alt"}, "v"},
    max_entries = 500,
    max_age_days = 30,
    max_menu_items = 5,
    poll_interval = 0.5,
}

local DATA_DIR = os.getenv("HOME") .. "/Library/Mobile Documents/com~apple~CloudDocs/ClipboardHistory"
local DATA_FILE = DATA_DIR .. "/history.json"

-- UTI types that indicate concealed/transient clipboard entries (password managers, text expanders)
local CONCEALED_TYPES = {
    ["org.nspasteboard.ConcealedType"] = true,
    ["org.nspasteboard.TransientType"] = true,
    ["org.nspasteboard.AutoGeneratedType"] = true,
    ["com.agilebits.onepassword"] = true,
    ["de.petermaurer.TransientPasteboardType"] = true,
    ["com.typeit4me.clipping"] = true,
}

-- Private state
local entries = {}
local watcher = nil
local webview = nil
local webviewVisible = false
local hotkeyBind = nil
local cleanupTimer = nil
local lastSetByUs = nil

-- Forward declarations
local loadFromDisk, persistToDisk, cleanupOld
local onClipboardChange, isConcealed
local showWebview, hideWebview, toggleWebview, pushEntriesToJS

-- Check if current clipboard content has concealed/transient UTI types
isConcealed = function()
    local ok, types = pcall(hs.pasteboard.contentTypes)
    if not ok or not types then return false end
    for _, t in ipairs(types) do
        if CONCEALED_TYPES[t] then
            return true
        end
    end
    return false
end

-- Load history from JSON file on disk
loadFromDisk = function()
    local f = io.open(DATA_FILE, "r")
    if not f then
        entries = {}
        return
    end
    local content = f:read("*a")
    f:close()
    if not content or content == "" then
        entries = {}
        return
    end
    local ok, decoded = pcall(hs.json.decode, content)
    if ok and type(decoded) == "table" then
        entries = decoded
    else
        print("clipboard_history: failed to decode history file, starting fresh")
        entries = {}
    end
end

-- Persist current entries to JSON file on disk
persistToDisk = function()
    hs.fs.mkdir(DATA_DIR)
    local ok, encoded = pcall(hs.json.encode, entries)
    if not ok then
        print("clipboard_history: failed to encode entries: " .. tostring(encoded))
        return
    end
    local f = io.open(DATA_FILE, "w")
    if not f then
        print("clipboard_history: failed to open file for writing: " .. DATA_FILE)
        return
    end
    f:write(encoded)
    f:close()
end

-- Remove entries older than max_age_days
cleanupOld = function()
    local cutoff = os.time() - (config.max_age_days * 86400)
    local cleaned = {}
    for _, entry in ipairs(entries) do
        -- Parse ISO timestamp: 2026-03-24T14:30:00
        local y, mo, d, h, mi, s = entry.timestamp:match("(%d+)-(%d+)-(%d+)T(%d+):(%d+):(%d+)")
        if y then
            local entryTime = os.time({year = tonumber(y), month = tonumber(mo), day = tonumber(d),
                                        hour = tonumber(h), min = tonumber(mi), sec = tonumber(s)})
            if entryTime >= cutoff then
                table.insert(cleaned, entry)
            end
        else
            -- Keep entries with unparseable timestamps rather than losing data
            table.insert(cleaned, entry)
        end
    end
    local removed = #entries - #cleaned
    if removed > 0 then
        print("clipboard_history: pruned " .. removed .. " entries older than " .. config.max_age_days .. " days")
        entries = cleaned
        persistToDisk()
    end
end

-- Clipboard change callback
onClipboardChange = function(text)
    -- Skip non-text content
    if not text or text == "" or text:match("^%s*$") then
        return
    end

    -- Skip entries we just set ourselves (from copy button or menu)
    if lastSetByUs and text == lastSetByUs then
        lastSetByUs = nil
        return
    end
    lastSetByUs = nil

    -- Skip concealed entries (passwords, text expanders)
    if isConcealed() then
        print("clipboard_history: skipping concealed clipboard entry")
        return
    end

    -- Dedup: skip if same as most recent entry
    if #entries > 0 and entries[1].text == text then
        return
    end

    -- Build entry
    local entry = {
        id = tostring(hs.timer.absoluteTime()),
        text = text,
        timestamp = os.date("%Y-%m-%dT%H:%M:%S"),
        app = "",
    }

    -- Get frontmost app name
    local ok, app = pcall(hs.application.frontmostApplication)
    if ok and app then
        entry.app = app:name() or ""
    end

    -- Prepend to entries (newest first)
    table.insert(entries, 1, entry)

    -- Cap entries
    while #entries > config.max_entries do
        table.remove(entries)
    end

    persistToDisk()

    -- Update webview if visible
    if webview and webviewVisible then
        pushEntriesToJS()
    end
end

-- Push entries to JS as JSON
pushEntriesToJS = function()
    if not webview or not webviewVisible then return end
    local ok, json = pcall(hs.json.encode, entries)
    if not ok then return end
    -- Escape for safe embedding in a JS single-quoted string literal
    json = json:gsub("\\", "\\\\"):gsub("'", "\\'"):gsub("\n", "\\n"):gsub("\r", "\\r")
    webview:evaluateJavaScript(string.format("if (window.loadEntries) window.loadEntries('%s')", json))
end

-- Show the clipboard history webview
showWebview = function()
    if not webview then
        local usercontent = hs.webview.usercontent.new("clipboardHistory")
            :setCallback(function(msg)
                if type(msg.body) ~= "table" then return end
                local action = msg.body.action
                if action == "copy" then
                    lastSetByUs = msg.body.text
                    hs.pasteboard.setContents(msg.body.text)
                elseif action == "delete" then
                    local targetId = msg.body.id
                    for i, entry in ipairs(entries) do
                        if entry.id == targetId then
                            table.remove(entries, i)
                            break
                        end
                    end
                    persistToDisk()
                    pushEntriesToJS()
                elseif action == "close" then
                    hideWebview()
                elseif action == "ready" then
                    pushEntriesToJS()
                end
            end)

        local screen = hs.mouse.getCurrentScreen():frame()
        local width = 720
        local height = 550
        local rect = {
            x = screen.x + (screen.w - width) / 2,
            y = screen.y + (screen.h - height) / 2,
            w = width,
            h = height
        }

        webview = hs.webview.new(rect, { developerExtrasEnabled = false }, usercontent)
            :allowTextEntry(true)
            :windowStyle({"titled", "closable", "resizable"})
            :windowTitle("Clipboard History")
            :closeOnEscape(false)
            :windowCallback(function(action, _wv, _state)
                if action == "closing" then
                    webviewVisible = false
                    webview = nil
                end
            end)

        webview:html(htmlLoader.load("clipboard_history"))
    end

    -- Reposition to cursor's screen each time
    local screen = hs.mouse.getCurrentScreen():frame()
    local width = 720
    local height = 550
    webview:frame({
        x = screen.x + (screen.w - width) / 2,
        y = screen.y + (screen.h - height) / 2,
        w = width,
        h = height
    })

    webview:evaluateJavaScript("if (window.resetUI) window.resetUI()")

    webview:show()
    webview:hswindow():focus()
    webviewVisible = true

    pushEntriesToJS()
end

hideWebview = function()
    if webview and webviewVisible then
        webview:hide()
        webviewVisible = false
    end
end

toggleWebview = function()
    if webviewVisible then
        hideWebview()
    else
        showWebview()
    end
end

-- Unified menu integration
function M.getMenuItems()
    local items = {}
    local count = math.min(#entries, config.max_menu_items)
    for i = 1, count do
        local e = entries[i]
        local display = e.text:gsub("\n", " "):sub(1, 40)
        if #e.text > 40 then display = display .. "..." end
        table.insert(items, {
            title = display,
            fn = function()
                lastSetByUs = e.text
                hs.pasteboard.setContents(e.text)
            end
        })
    end
    if #entries > 0 then
        table.insert(items, { title = "-" })
    end
    table.insert(items, { title = "Show History...", fn = function() showWebview() end })
    return items
end

-- Public API

function M.init(cfg)
    cfg = cfg or {}
    for k, v in pairs(cfg) do config[k] = v end

    loadFromDisk()
    cleanupOld()

    watcher = hs.pasteboard.watcher.new(onClipboardChange)
    -- NOTE: interval() is a global setting that affects all pasteboard watchers
    hs.pasteboard.watcher.interval(config.poll_interval)
    watcher:start()

    hotkeyBind = hs.hotkey.bind(config.hotkey[1], config.hotkey[2], toggleWebview)
    cleanupTimer = hs.timer.doEvery(3600, cleanupOld)

    print("Clipboard History loaded (Ctrl+Alt+V to show)")
    return M
end

function M.stop()
    if watcher then watcher:stop(); watcher = nil end
    if hotkeyBind then hotkeyBind:delete(); hotkeyBind = nil end
    if cleanupTimer then cleanupTimer:stop(); cleanupTimer = nil end
    if webview then webview:delete(); webview = nil end
    webviewVisible = false
    entries = {}
    print("Clipboard History stopped")
end

return M
